[pytest]
# Python'un ana dizini ve alt klasörleri görmesini sağlar
pythonpath = .
testpaths = tests
# Logları terminalde renkli ve şık görmek için:
addopts = -v -n auto --alluredir=allure-results --reruns 2 --reruns-delay 1 --env prod