
name: Elite Playwright Tests CI (Dockerized)

permissions:
  contents: write
  pages: write
  id-token: write

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - prod

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1.Build Docker Image
      - name: Build Docker Image
        run: docker build -t elite-playwright-app .

      # 2. Ruun test In Docker container
      - name: Run Tests in Docker
        continue-on-error: true
        run: |
          mkdir -p allure-results
          docker run --name elite-container \
            -v ${{ github.workspace }}/allure-results:/app/allure-results \
            -e TEST_ENV=${{ github.event.inputs.environment || 'qa' }} \
            -e BASE_URL=${{ (github.event.inputs.environment == 'prod') && secrets.PROD_BASE_URL || secrets.QA_BASE_URL }} \
            -e STANDARD_USER=${{ (github.event.inputs.environment == 'prod') && secrets.PROD_USER || secrets.QA_USER }} \
            -e PASSWORD=${{ (github.event.inputs.environment == 'prod') && secrets.PROD_PASSWORD || secrets.QA_PASSWORD }} \
            elite-playwright-app \
            python -m pytest tests/ --alluredir=allure-results -n 2

      # 3. Prepare allure report
      - name: Build Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          enable_jekyll: false 
          force_orphan: true